/* CRIANDO O BANCO DE DADOS */
CREATE DATABASE PROJETOBD01
/* USANDO O BANCO DE DADOS */
USE PROJETOBD01


/* CRIANDO AS TABELAS DO BANCO DE DADOS */

CREATE TABLE FUNCIONARIO(
COD_FUNC INT PRIMARY KEY IDENTITY,
NOME_FUNC VARCHAR(50)
)
CREATE TABLE CLIENTE(
COD_CLIENT INT PRIMARY KEY IDENTITY,
NOME_CLIENT VARCHAR(50),
)
CREATE TABLE PRODUTO(
COD_PROD INT PRIMARY KEY IDENTITY,
NOME_PROD VARCHAR(80),
QUANT_PROD INT,
)

CREATE TABLE CARRINHO(
COD_CARRI INT PRIMARY KEY IDENTITY
)

CREATE TABLE VENDA(
COD_VEN INT PRIMARY KEY IDENTITY,
DESC_VEN VARCHAR(50)
)

/* ALTERANDO COISAS NA TABELA */
ALTER TABLE PRODUTO
ADD FK_COD_CLIENT INT
FOREIGN KEY(FK_COD_CLIENT) REFERENCES CLIENTE(COD_CLIENT)

ALTER TABLE CARRINHO
ADD FK_COD_PROD INT
FOREIGN KEY(FK_COD_PROD) REFERENCES PRODUTO(COD_PROD)

ALTER TABLE VENDA
ADD FOR_VEN VARCHAR(20)

ALTER TABLE VENDA 
ADD FK_COD_CARRI INT
FOREIGN KEY(FK_COD_CARRI) REFERENCES CARRINHO(COD_CARRI)



/*CONSULTAR TABELAS */

SELECT * FROM FUNCIONARIO
SELECT * FROM CLIENTE 
SELECT * FROM PRODUTO
SELECT * FROM CARRINHO
SELECT * FROM VENDA

/* INSERINDO INFORMAÇÕES NA TABELA */

INSERT INTO FUNCIONARIO(NOME_FUNC) VALUES('CADU MAVERICK')

INSERT INTO CLIENTE(NOME_CLIENT) VALUES('BIG Z')

INSERT INTO PRODUTO(NOME_PROD,QUANT_PROD,FK_COD_CLIENT) VALUES('TECLADO MECANICO',2,1)

INSERT INTO CARRINHO(FK_COD_PROD) VALUES (1)

INSERT INTO VENDA(DESC_VEN,FOR_VEN,FK_COD_CARRI) VALUES('TECLADO HYPERX BRANCO', 'DINHEIRO',1)

/* OUTRO INSERT INTO */ 

INSERT INTO CLIENTE(NOME_CLIENT) VALUES('TANK TRITURADOR EVANS')

INSERT INTO PRODUTO(NOME_PROD,QUANT_PROD,FK_COD_CLIENT) VALUES('MOUSE RGB',1,2)

INSERT INTO CARRINHO(FK_COD_PROD) VALUES (2)

INSERT INTO VENDA(DESC_VEN,FOR_VEN,FK_COD_CARRI) VALUES('MOUSE RGB PRETO', 'CARTAO',2)